# Generated by Django 4.2 on 2023-08-30 08:40

import collector.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='file',
            field=models.FileField(upload_to=collector.utils.logs_dir_path),
        ),
    ]
