# Generated by Django 4.2 on 2023-08-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-time_create']},
        ),
        migrations.AlterField(
            model_name='archive',
            name='size',
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
