# Generated by Django 4.2 on 2023-08-08 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_alter_ticket_options_alter_archive_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='ticket',
            field=models.ForeignKey(db_column='ticket_number', on_delete=django.db.models.deletion.CASCADE, to='collector.ticket', to_field='number'),
        ),
    ]
