# Generated by Django 4.2 on 2023-08-08 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_alter_archive_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='sha1',
            new_name='md5',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='size',
        ),
    ]
