# Generated by Django 4.2 on 2023-08-08 16:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0005_token_archive_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='token',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='upload',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='platform',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='platform',
            field=models.ForeignKey(db_column='platform_name', on_delete=django.db.models.deletion.CASCADE, to='collector.platform', to_field='name'),
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
