# Generated by Django 4.2 on 2023-08-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_remove_archive_token_remove_archive_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='upload',
            new_name='attempts',
        ),
    ]
