# Generated by Django 4.2 on 2023-08-10 03:24

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0007_rename_upload_ticket_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='attempts',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
